name: docs
on: [push]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy Ecosystem
        uses: actions/checkout@v2
        with:
          path: ivy_ecosystem
          persist-credentials: false

      - name: Build Docs
        run: |
          docker run --rm -v ivy_ecosystem:/project unifyai/doc-builder:latest

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ivy_ecosystem/docs/build
          CLEAN: false
          GIT_CONFIG_NAME: ivy-seed
          GIT_CONFIG_EMAIL: ivydl.team@gmail.com
